version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=abcd@1234
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    volumes:
      - mssql:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8000M
        reservations:
          cpus: '0.25'
          memory: 500M  
volumes:
  mssql:
